# Generated by Django 2.1.5 on 2019-01-19 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hours',
            field=wagtail.core.fields.StreamField([('hour_info', wagtail.core.blocks.CharBlock())], null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 19, 20, 21, 54, 558384, tzinfo=utc)),
        ),
    ]
