# Generated by Django 2.1.5 on 2019-01-28 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190120_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 28, 20, 55, 13, 682568, tzinfo=utc)),
        ),
    ]
