# Generated by Django 2.1.5 on 2019-01-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='about_content',
        ),
    ]
