# Generated by Django 2.1.5 on 2019-01-19 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190119_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 19, 23, 3, 40, 668204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pricingsection',
            name='body',
            field=wagtail.core.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'renderer': 'html'}))], blank=True),
        ),
    ]
