# Generated by Django 2.1.5 on 2019-01-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='layout_lab_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
