# Generated by Django 2.1.7 on 2019-02-27 22:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190220_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
